import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import LayoutWithSidebar from '@/components/LayoutWithSidebar';

const inter = Inter({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Case Request App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR">
      <body
        className={`${inter.className} antialiased`}
      >
         <LayoutWithSidebar>{children}</LayoutWithSidebar>
      </body>
    </html>
  );
}
